.TH COLLECTL-FILES 1 "APRIL 2003" LOCAL "Collectl" -*- nroff -*-
.SH FILES

There are just too many of these to clutter up the main man page with

.I /etc/collectl.conf

.I /proc/pid/stat

.I /proc/pid/status

.I /proc/cpqfan

.I /proc/cpqpwr

.I /proc/cpqtemp

.I /proc/fs/lustre/llite/fs*/stats

.I /proc/fs/lustre/osc/OST_...client.../stats

.I /proc/fs/lustre/obdfilter/OST_.../stats

.I /proc/fs/lustre/obdfilter/OST_.../brw_stats

.I /proc/fs/lustre/osc/OSC...mds.../stats

.I /proc/loadavg

.I /proc/meminfo

.I /proc/net/dev

.I /proc/net/netstat

.I /proc/net/rpc/nfs

.I /proc/net/rpc/nfsd

.I /proc/net/sockstat

.I /proc/partitions

.I /proc/qsnet/ep/rail[0-1]/stats

.I /proc/slabinfo

.I /proc/stat

.I /proc/sys/fs/dentry-state

.I /proc/sys/fs/inode-state

.I /proc/sys/fs/file-nr

.I /proc/sys/fs/super-nr

.I /proc/sys/fs/dquot-nt

.SH AUTHOR
Copyright 2003-2007 Hewlett-Packard Development Company, LP
collectl may be copied only under the terms of either the Artistic License
or the GNU General Public License, which may be found in the source kit
