#!/bin/bash

BINDIR=/usr/bin
DOCDIR=/usr/share/doc/collectl
SHRDIR=/usr/share/collectl

mkdir -p $DOCDIR
mkdir -p $SHRDIR
mkdir -p $SHRDIR/util
mkdir -p /var/log/collectl

cp collectl.pl           $BINDIR/collectl
cp collectl.conf         /etc
cp initd/*               /etc/init.d
cp man1/*                /usr/share/man/man1

cp docs/*                $DOCDIR
cp GPL ARTISTIC COPYING  $DOCDIR
cp RELEASE-collectl      $DOCDIR

cp UNINSTALL             $SHRDIR
cp formatit.ph           $SHRDIR
cp lexpr.ph sexpr.ph     $SHRDIR
cp gexpr.ph misc.ph      $SHRDIR
cp envrules.std          $SHRDIR
cp vmstat.ph             $SHRDIR
cp client.pl readS       $SHRDIR/util
cp col2tlviz.pl          $SHRDIR/util

# Force in case redoing the install and files already zipped
gzip -f /usr/share/man/man1/collectl*

chmod 755 /etc/init.d/collectl*
chmod 444 /etc/collectl.conf
chmod 755 $BINDIR/collectl
chmod 444 $DOCDIR/ARTISTIC $DOCDIR/COPYING $DOCDIR/GPL
chmod 755 $SHRDIR/util/*
chmod 444 $SHRDIR/formatit.ph $SHRDIR/*expr.ph $SHRDIR/vmstat.ph

# remove any stale versions in case the names/numbers used have changed.
# on new ROCKS installion 'rm' isn't there yet!  [thanks roy]
if [ -x /bin/rm ] ; then
  /bin/rm -f /etc/init.d/rc*.d/*collectl
  /bin/rm -f /etc/rc.d/rc*.d/*collectl
fi

# Try and decide which distro this is based on distro specific files.
distro=1
if [[ -f /sbin/yast ]]; then
    distro=2
    cp -f /etc/init.d/collectl-suse /etc/init.d/collectl
    rm -f /etc/init.d/collectl-suse
    rm -f /etc/init.d/collectl-debian
    rm -f /etc/init.d/collectl-generic
fi

# debian
if [[ -f /usr/sbin/update-rc.d ]]; then
    distro=3
    cp -f /etc/init.d/collectl-debian /etc/init.d/collectl
    rm -f /etc/init.d/collectl-suse
    rm -f /etc/init.d/collectl-debian
    rm -f /etc/init.d/collectl-generic
    update-rc.d collectl defaults
fi

# redhat
if [[ -f /etc/redhat-release ]]; then
    distro=4
    rm -f /etc/init.d/collectl-suse
    rm -f /etc/init.d/collectl-debian
    rm -f /etc/init.d/collectl-generic
    chkconfig --add collectl
fi

# gentoo
if [[ -f /etc/gentoo-release ]]; then
    distro=5
    cp -f /etc/init.d/collectl-generic /etc/init.d/collectl
    rm -f /etc/init.d/collectl-suse
    rm -f /etc/init.d/collectl-debian
    rm -f /etc/init.d/collectl-generic
    rc-update -a collectl default
fi

# Generic Distros
# If /etc/init.d doesn't exist and/or there's no way to use chkconfig or 
# rc-update you're going to have to add some custom code below...
if [[ ${distro} = 1 ]]; then

    cp -f /etc/init.d/collectl-generic /etc/init.d/collectl
    rm -f /etc/init.d/collectl-suse
    rm -f /etc/init.d/collectl-debian
    rm -f /etc/init.d/collectl-generic

    # figure out how to handle reboots
    if [[ -f /sbin/chkconfig ]]; then
        chkconfig --add collectl
    elif [[ -f /sbin/rc-update ]]; then
        rc-update -a collectl default
    else
        echo "could not figure out how to enable restarting across reboots"
    fi
fi
