#!/bin/bash

BINDIR=/opt/hp/collectl

mkdir -p $BINDIR
mkdir -p $BINDIR/sbin
mkdir -p $BINDIR/docs
mkdir -p $BINDIR/man1
mkdir -p $BINDIR/etc/init.d

cp GPL ARTISTIC COPYING  $BINDIR
cp UNINSTALL             $BINDIR
cp RELEASE-collectl      $BINDIR/docs

cp collectl.pl           $BINDIR/sbin/collectl
cp formatit.ph           $BINDIR/sbin
cp lexpr.ph sexpr.ph     $BINDIR/sbin
cp gexpr.ph misc.ph      $BINDIR/sbin
cp envrules.std          $BINDIR/sbin
cp vmstat.ph readS       $BINDIR/sbin
cp collectl.conf         $BINDIR/etc
cp docs/*                $BINDIR/docs
cp initd/*               $BINDIR/etc/init.d
cp man1/*                $BINDIR/man1

# Force in case redoing the install and files already zipped
gzip -f $BINDIR/man1/*

chmod 755 $BINDIR/sbin/collectl $BINDIR/sbin/readS
chmod 755 $BINDIR//etc/init.d/collectl
chmod 444 $BINDIR/sbin/formatit.ph $BINDIR/sbin/*expr.ph $BINDIR/sbin/vmstat.ph
chmod 444 $BINDIR/etc/collectl.conf
chmod 444 $BINDIR/ARTISTIC $BINDIR/COPYING $BINDIR/GPL

# create all symlinks, noting daemon start link may get changed later
ln -sf $BINDIR/man1/collectl.1.gz  /usr/share/man/man1/collectl.1.gz
ln -sf $BINDIR/sbin/collectl       /usr/bin/collectl
ln -sf $BINDIR/sbin/collectl       /usr/sbin/collectl
ln -sf $BINDIR/etc/collectl.conf   /etc/collectl.conf
ln -sf $BINDIR/etc/init.d/collectl /etc/init.d/collectl

# remove any stale versions in case the names numbers used have changed.
# on new ROCKS installion 'rm' isn't there yet!  [thanks roy]
if [ -x /bin/rm ] ; then
  /bin/rm -f /etc/init.d/rc*.d/*collectl
  /bin/rm -f /etc/rc.d/rc*.d/*collectl
fi

# Try and decide which distro this is based on distro specific files.
distro=1
if [[ -f /sbin/yast ]]; then
    distro=2
    ln -sf $BINDIR/etc/init.d/collectl-suse /etc/init.d/collectl
fi

# debian
if [[ -f /usr/sbin/update-rc.d ]]; then
    distro=3
    ln -sf $BINDIR/etc/init.d/collectl-debian /etc/init.d/collectl
    chmod +x /etc/init.d/collectl
    update-rc.d collectl defaults
fi

# redhat
if [[ -f /etc/redhat-release ]]; then
    distro=4
    chkconfig --add collectl
fi

if [[ ${distro} = 1 ]]; then
    ln -sf /etc/rc.d/init.d/collectl /etc/rc.d/rc5.d/K99collectl
fi
